Not Found: /
Not Found: /
Not Found: /favicon.ico
Not Found: /
Not Found: /
Not Found: /favicon.ico
Not Found: /
Not Found: /
Not Found: /
Not Found: /maparea/maparea/login
Not Found: /maparea/maparea/login
Not Found: /maparea/maparea/login
Internal Server Error: /maparea/savepolygon
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 87, in get_response
    response = middleware_method(request)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/middleware.py", line 34, in process_request
    if user and hasattr(user, 'get_session_auth_hash'):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 224, in inner
    self._setup()
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 357, in _setup
    self._wrapped = self._setupfunc()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/middleware.py", line 23, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/middleware.py", line 11, in get_user
    request._cached_user = auth.get_user(request)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/__init__.py", line 151, in get_user
    user_id = request.session[SESSION_KEY]
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/base.py", line 49, in __getitem__
    return self._session[key]
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/base.py", line 175, in _get_session
    self._session_cache = self.load()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/db.py", line 21, in load
    expire_date__gt=timezone.now()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 351, in get
    num = len(clone)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 122, in __len__
    self._fetch_all()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 966, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 265, in iterator
    for row in compiler.results_iter():
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 700, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 784, in execute_sql
    cursor = self.connection.cursor()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 165, in cursor
    cursor = self.make_debug_cursor(self._cursor())
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 138, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 133, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 133, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 122, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/sqlite3/base.py", line 374, in get_new_connection
    conn = Database.connect(**conn_params)
OperationalError: unable to open database file
Internal Server Error: /maparea/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 87, in get_response
    response = middleware_method(request)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/middleware.py", line 34, in process_request
    if user and hasattr(user, 'get_session_auth_hash'):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 224, in inner
    self._setup()
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 357, in _setup
    self._wrapped = self._setupfunc()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/middleware.py", line 23, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/middleware.py", line 11, in get_user
    request._cached_user = auth.get_user(request)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/__init__.py", line 151, in get_user
    user_id = request.session[SESSION_KEY]
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/base.py", line 49, in __getitem__
    return self._session[key]
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/base.py", line 175, in _get_session
    self._session_cache = self.load()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/db.py", line 21, in load
    expire_date__gt=timezone.now()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 351, in get
    num = len(clone)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 122, in __len__
    self._fetch_all()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 966, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 265, in iterator
    for row in compiler.results_iter():
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 700, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 784, in execute_sql
    cursor = self.connection.cursor()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 165, in cursor
    cursor = self.make_debug_cursor(self._cursor())
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 138, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 133, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 133, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 122, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/sqlite3/base.py", line 374, in get_new_connection
    conn = Database.connect(**conn_params)
OperationalError: unable to open database file
Internal Server Error: /maparea/savepolygon
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 87, in get_response
    response = middleware_method(request)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/middleware.py", line 34, in process_request
    if user and hasattr(user, 'get_session_auth_hash'):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 224, in inner
    self._setup()
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 357, in _setup
    self._wrapped = self._setupfunc()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/middleware.py", line 23, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/middleware.py", line 11, in get_user
    request._cached_user = auth.get_user(request)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/__init__.py", line 151, in get_user
    user_id = request.session[SESSION_KEY]
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/base.py", line 49, in __getitem__
    return self._session[key]
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/base.py", line 175, in _get_session
    self._session_cache = self.load()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/db.py", line 21, in load
    expire_date__gt=timezone.now()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 351, in get
    num = len(clone)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 122, in __len__
    self._fetch_all()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 966, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 265, in iterator
    for row in compiler.results_iter():
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 700, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 784, in execute_sql
    cursor = self.connection.cursor()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 165, in cursor
    cursor = self.make_debug_cursor(self._cursor())
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 138, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 133, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 133, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 122, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/sqlite3/base.py", line 374, in get_new_connection
    conn = Database.connect(**conn_params)
OperationalError: unable to open database file
Internal Server Error: /maparea/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 87, in get_response
    response = middleware_method(request)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/middleware.py", line 34, in process_request
    if user and hasattr(user, 'get_session_auth_hash'):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 224, in inner
    self._setup()
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 357, in _setup
    self._wrapped = self._setupfunc()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/middleware.py", line 23, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/middleware.py", line 11, in get_user
    request._cached_user = auth.get_user(request)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/__init__.py", line 151, in get_user
    user_id = request.session[SESSION_KEY]
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/base.py", line 49, in __getitem__
    return self._session[key]
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/base.py", line 175, in _get_session
    self._session_cache = self.load()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/db.py", line 21, in load
    expire_date__gt=timezone.now()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 351, in get
    num = len(clone)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 122, in __len__
    self._fetch_all()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 966, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 265, in iterator
    for row in compiler.results_iter():
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 700, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 784, in execute_sql
    cursor = self.connection.cursor()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 165, in cursor
    cursor = self.make_debug_cursor(self._cursor())
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 138, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 133, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 133, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 122, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/sqlite3/base.py", line 374, in get_new_connection
    conn = Database.connect(**conn_params)
OperationalError: unable to open database file
Internal Server Error: /maparea/savepolygon
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 87, in get_response
    response = middleware_method(request)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/middleware.py", line 34, in process_request
    if user and hasattr(user, 'get_session_auth_hash'):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 224, in inner
    self._setup()
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 357, in _setup
    self._wrapped = self._setupfunc()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/middleware.py", line 23, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/middleware.py", line 11, in get_user
    request._cached_user = auth.get_user(request)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/__init__.py", line 151, in get_user
    user_id = request.session[SESSION_KEY]
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/base.py", line 49, in __getitem__
    return self._session[key]
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/base.py", line 175, in _get_session
    self._session_cache = self.load()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/db.py", line 21, in load
    expire_date__gt=timezone.now()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 351, in get
    num = len(clone)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 122, in __len__
    self._fetch_all()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 966, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 265, in iterator
    for row in compiler.results_iter():
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 700, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 784, in execute_sql
    cursor = self.connection.cursor()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 165, in cursor
    cursor = self.make_debug_cursor(self._cursor())
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 138, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 133, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 133, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 122, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/sqlite3/base.py", line 374, in get_new_connection
    conn = Database.connect(**conn_params)
OperationalError: unable to open database file
Internal Server Error: /maparea/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 87, in get_response
    response = middleware_method(request)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/middleware.py", line 34, in process_request
    if user and hasattr(user, 'get_session_auth_hash'):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 224, in inner
    self._setup()
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 357, in _setup
    self._wrapped = self._setupfunc()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/middleware.py", line 23, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/middleware.py", line 11, in get_user
    request._cached_user = auth.get_user(request)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/__init__.py", line 151, in get_user
    user_id = request.session[SESSION_KEY]
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/base.py", line 49, in __getitem__
    return self._session[key]
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/base.py", line 175, in _get_session
    self._session_cache = self.load()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/db.py", line 21, in load
    expire_date__gt=timezone.now()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 351, in get
    num = len(clone)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 122, in __len__
    self._fetch_all()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 966, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 265, in iterator
    for row in compiler.results_iter():
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 700, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 784, in execute_sql
    cursor = self.connection.cursor()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 165, in cursor
    cursor = self.make_debug_cursor(self._cursor())
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 138, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 133, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 133, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 122, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/sqlite3/base.py", line 374, in get_new_connection
    conn = Database.connect(**conn_params)
OperationalError: unable to open database file
Internal Server Error: /admin/maparea/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 87, in get_response
    response = middleware_method(request)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/middleware.py", line 34, in process_request
    if user and hasattr(user, 'get_session_auth_hash'):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 224, in inner
    self._setup()
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 357, in _setup
    self._wrapped = self._setupfunc()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/middleware.py", line 23, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/middleware.py", line 11, in get_user
    request._cached_user = auth.get_user(request)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/__init__.py", line 151, in get_user
    user_id = request.session[SESSION_KEY]
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/base.py", line 49, in __getitem__
    return self._session[key]
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/base.py", line 175, in _get_session
    self._session_cache = self.load()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/db.py", line 21, in load
    expire_date__gt=timezone.now()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 351, in get
    num = len(clone)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 122, in __len__
    self._fetch_all()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 966, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 265, in iterator
    for row in compiler.results_iter():
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 700, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 784, in execute_sql
    cursor = self.connection.cursor()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 165, in cursor
    cursor = self.make_debug_cursor(self._cursor())
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 138, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 133, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 133, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 122, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/sqlite3/base.py", line 374, in get_new_connection
    conn = Database.connect(**conn_params)
OperationalError: unable to open database file
Internal Server Error: /admin/maparea/polygon/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 137, in get_response
    response = response.render()
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 103, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 80, in rendered_content
    content = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 148, in render
    return self._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 126, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 126, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 1207, in render
    _dict = func(*resolved_args, **resolved_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/templatetags/admin_list.py", line 316, in result_list
    'results': list(results(cl))}
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/templatetags/admin_list.py", line 292, in results
    yield ResultList(None, items_for_result(cl, res, None))
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/templatetags/admin_list.py", line 283, in __init__
    super(ResultList, self).__init__(*items)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/templatetags/admin_list.py", line 198, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/utils.py", line 280, in lookup_field
    value = attr()
  File "/home/medson/workspace/frossard/polygons/polygons/maparea/models.py", line 21, in __str__
    return self.user.username + " " + self.polygon
AttributeError: 'Polygon' object has no attribute 'polygon'
Internal Server Error: /admin/maparea/polygon/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 137, in get_response
    response = response.render()
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 103, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 80, in rendered_content
    content = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 148, in render
    return self._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 126, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 126, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 1207, in render
    _dict = func(*resolved_args, **resolved_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/templatetags/admin_list.py", line 316, in result_list
    'results': list(results(cl))}
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/templatetags/admin_list.py", line 292, in results
    yield ResultList(None, items_for_result(cl, res, None))
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/templatetags/admin_list.py", line 283, in __init__
    super(ResultList, self).__init__(*items)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/templatetags/admin_list.py", line 198, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/utils.py", line 280, in lookup_field
    value = attr()
  File "/home/medson/workspace/frossard/polygons/polygons/maparea/models.py", line 21, in __str__
    return self.user.username + " " + self.polygon
AttributeError: 'Polygon' object has no attribute 'polygon'
Internal Server Error: /admin/maparea/polygon/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 137, in get_response
    response = response.render()
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 103, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 80, in rendered_content
    content = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 148, in render
    return self._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 126, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 126, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 1207, in render
    _dict = func(*resolved_args, **resolved_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/templatetags/admin_list.py", line 316, in result_list
    'results': list(results(cl))}
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/templatetags/admin_list.py", line 292, in results
    yield ResultList(None, items_for_result(cl, res, None))
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/templatetags/admin_list.py", line 283, in __init__
    super(ResultList, self).__init__(*items)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/templatetags/admin_list.py", line 198, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/utils.py", line 280, in lookup_field
    value = attr()
  File "/home/medson/workspace/frossard/polygons/polygons/maparea/models.py", line 21, in __str__
    return self.user.username + " " + self.polygon
AttributeError: 'Polygon' object has no attribute 'polygon'
Not Found: /
Not Found: /
Internal Server Error: /admin/maparea/polygon/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 137, in get_response
    response = response.render()
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 103, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 80, in rendered_content
    content = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 148, in render
    return self._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 126, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 126, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 1207, in render
    _dict = func(*resolved_args, **resolved_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/templatetags/admin_list.py", line 316, in result_list
    'results': list(results(cl))}
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/templatetags/admin_list.py", line 292, in results
    yield ResultList(None, items_for_result(cl, res, None))
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/templatetags/admin_list.py", line 283, in __init__
    super(ResultList, self).__init__(*items)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/templatetags/admin_list.py", line 198, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/utils.py", line 280, in lookup_field
    value = attr()
  File "/home/medson/workspace/frossard1/polygons/polygons/maparea/models.py", line 21, in __str__
    return self.user.username + " " + self.polygon
AttributeError: 'Polygon' object has no attribute 'polygon'
Not Found: /
Not Found: /
Not Found: /favicon.ico
Not Found: /
Not Found: /favicon.ico
Not Found: /maparea/maparea/login
Not Found: /favicon.ico
Not Found: /favicon.ico
Internal Server Error: /admin/maparea/polygon/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 137, in get_response
    response = response.render()
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 103, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 80, in rendered_content
    content = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 148, in render
    return self._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 126, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 126, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 1207, in render
    _dict = func(*resolved_args, **resolved_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/templatetags/admin_list.py", line 316, in result_list
    'results': list(results(cl))}
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/templatetags/admin_list.py", line 292, in results
    yield ResultList(None, items_for_result(cl, res, None))
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/templatetags/admin_list.py", line 283, in __init__
    super(ResultList, self).__init__(*items)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/templatetags/admin_list.py", line 198, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/utils.py", line 280, in lookup_field
    value = attr()
  File "/home/medson/workspace/frossard1/polygons/polygons/maparea/models.py", line 21, in __str__
    return self.user.username + " " + self.polygon
AttributeError: 'Polygon' object has no attribute 'polygon'
Internal Server Error: /admin/maparea/polygon/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 137, in get_response
    response = response.render()
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 103, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 80, in rendered_content
    content = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 148, in render
    return self._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 126, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 126, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 1207, in render
    _dict = func(*resolved_args, **resolved_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/templatetags/admin_list.py", line 316, in result_list
    'results': list(results(cl))}
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/templatetags/admin_list.py", line 292, in results
    yield ResultList(None, items_for_result(cl, res, None))
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/templatetags/admin_list.py", line 283, in __init__
    super(ResultList, self).__init__(*items)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/templatetags/admin_list.py", line 198, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/utils.py", line 280, in lookup_field
    value = attr()
  File "/home/medson/workspace/frossard1/polygons/polygons/maparea/models.py", line 21, in __str__
    return self.user.username + " " + self.polygon
AttributeError: 'Polygon' object has no attribute 'polygon'
Internal Server Error: /admin/maparea/polygon/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 137, in get_response
    response = response.render()
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 103, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 80, in rendered_content
    content = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 148, in render
    return self._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 126, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 126, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 1207, in render
    _dict = func(*resolved_args, **resolved_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/templatetags/admin_list.py", line 316, in result_list
    'results': list(results(cl))}
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/templatetags/admin_list.py", line 292, in results
    yield ResultList(None, items_for_result(cl, res, None))
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/templatetags/admin_list.py", line 283, in __init__
    super(ResultList, self).__init__(*items)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/templatetags/admin_list.py", line 198, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/utils.py", line 280, in lookup_field
    value = attr()
  File "/home/medson/workspace/frossard1/polygons/polygons/maparea/models.py", line 21, in __str__
    return self.user.username + " " + self.polygon
AttributeError: 'Polygon' object has no attribute 'polygon'
Internal Server Error: /admin/maparea/polygon/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 137, in get_response
    response = response.render()
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 103, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 80, in rendered_content
    content = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 148, in render
    return self._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 126, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 126, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 1207, in render
    _dict = func(*resolved_args, **resolved_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/templatetags/admin_list.py", line 316, in result_list
    'results': list(results(cl))}
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/templatetags/admin_list.py", line 292, in results
    yield ResultList(None, items_for_result(cl, res, None))
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/templatetags/admin_list.py", line 283, in __init__
    super(ResultList, self).__init__(*items)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/templatetags/admin_list.py", line 198, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/utils.py", line 280, in lookup_field
    value = attr()
  File "/home/medson/workspace/frossard1/polygons/polygons/maparea/models.py", line 21, in __str__
    return self.user.username + " " + self.polygon
TypeError: coercing to Unicode: need string or buffer, int found
Not Found: /
Not Found: /
Internal Server Error: /admin/maparea/polygon/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 137, in get_response
    response = response.render()
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 103, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 80, in rendered_content
    content = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 148, in render
    return self._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 126, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 126, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 1207, in render
    _dict = func(*resolved_args, **resolved_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/templatetags/admin_list.py", line 316, in result_list
    'results': list(results(cl))}
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/templatetags/admin_list.py", line 292, in results
    yield ResultList(None, items_for_result(cl, res, None))
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/templatetags/admin_list.py", line 283, in __init__
    super(ResultList, self).__init__(*items)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/templatetags/admin_list.py", line 198, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/utils.py", line 280, in lookup_field
    value = attr()
  File "/home/medson/workspace/frossard1/polygons/polygons/maparea/models.py", line 21, in __str__
    return self.user.username + " " + self.polygon
AttributeError: 'Polygon' object has no attribute 'polygon'
Internal Server Error: /admin/maparea/polygon/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 137, in get_response
    response = response.render()
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 103, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 80, in rendered_content
    content = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 148, in render
    return self._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 126, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 126, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 1207, in render
    _dict = func(*resolved_args, **resolved_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/templatetags/admin_list.py", line 316, in result_list
    'results': list(results(cl))}
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/templatetags/admin_list.py", line 292, in results
    yield ResultList(None, items_for_result(cl, res, None))
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/templatetags/admin_list.py", line 283, in __init__
    super(ResultList, self).__init__(*items)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/templatetags/admin_list.py", line 198, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/utils.py", line 280, in lookup_field
    value = attr()
  File "/home/medson/workspace/frossard1/polygons/polygons/maparea/models.py", line 21, in __str__
    #    return self.user.username + " " + self.polygon
AttributeError: 'Polygon' object has no attribute 'polygon'
Internal Server Error: /admin/maparea/polygon/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 137, in get_response
    response = response.render()
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 103, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 80, in rendered_content
    content = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 148, in render
    return self._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 126, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 126, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 1207, in render
    _dict = func(*resolved_args, **resolved_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/templatetags/admin_list.py", line 316, in result_list
    'results': list(results(cl))}
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/templatetags/admin_list.py", line 292, in results
    yield ResultList(None, items_for_result(cl, res, None))
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/templatetags/admin_list.py", line 283, in __init__
    super(ResultList, self).__init__(*items)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/templatetags/admin_list.py", line 198, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/utils.py", line 280, in lookup_field
    value = attr()
  File "/home/medson/workspace/frossard1/polygons/polygons/maparea/models.py", line 21, in __str__
    #    return self.user.username + " " + self.polygon
AttributeError: 'Polygon' object has no attribute 'polygon'
Not Found: /
Not Found: /
Not Found: /polygons
Not Found: /
Not Found: /
Not Found: /maparea/
Not Found: /
Not Found: /maparea/polygons/all
Not Found: /maparea/polygons/all
Not Found: /maparea/admin/
Not Found: /maparea/query
Not Found: /maparea/query
Not Found: /maparea/admin/
Not Found: /maparea/admin/
Not Found: /maparea/savepolygon
Not Found: /maparea/admin/
Not Found: /maparea/admin/
Not Found: /maparea/savepolygon
Not Found: /maparea/admin/
Not Found: /
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /maparea/maparea/login
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /
Not Found: /favicon.ico
Not Found: /maparea/maparea/login
Not Found: /maparea/maparea/login
Not Found: /favicon.ico
Not Found: /maparea/maparea/login
Not Found: /favicon.ico
Not Found: /maparea/maparea/login
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /maparea/maparea/login
Not Found: /favicon.ico
Internal Server Error: /maparea/
Traceback (most recent call last):
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Larisse\Documents\Workspace\fross\altaflora\maparea\views.py", line 16, in wrapper
    return method(request)
  File "C:\Users\Larisse\Documents\Workspace\fross\altaflora\maparea\views.py", line 32, in index
    return render(request, 'maparea/index.html', context)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\shortcuts.py", line 48, in render
    return HttpResponse(loader.render_to_string(*args, **kwargs),
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\loader.py", line 170, in render_to_string
    t = get_template(template_name, dirs)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\loader.py", line 144, in get_template
    template, origin = find_template(template_name, dirs)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\loader.py", line 132, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\loader.py", line 44, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\pyjade\ext\django\loader.py", line 70, in load_template
    template, origin = self.find_template(template_name, template_dirs)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\pyjade\ext\django\loader.py", line 38, in find_template
    template, display_name = loader(name, dirs)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\loader.py", line 44, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\loader.py", line 50, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\loader.py", line 156, in get_template_from_string
    return Template(source, origin, name)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\base.py", line 132, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\base.py", line 162, in compile_string
    return parser.parse()
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\base.py", line 288, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\base.py", line 344, in invalid_block_tag
    raise self.error(token, "Invalid block tag: '%s'" % command)
TemplateSyntaxError: Invalid block tag: 'static'
Internal Server Error: /maparea/
Traceback (most recent call last):
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Larisse\Documents\Workspace\fross\altaflora\maparea\views.py", line 16, in wrapper
    return method(request)
  File "C:\Users\Larisse\Documents\Workspace\fross\altaflora\maparea\views.py", line 32, in index
    return render(request, 'maparea/index.html', context)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\shortcuts.py", line 48, in render
    return HttpResponse(loader.render_to_string(*args, **kwargs),
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\loader.py", line 170, in render_to_string
    t = get_template(template_name, dirs)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\loader.py", line 144, in get_template
    template, origin = find_template(template_name, dirs)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\loader.py", line 132, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\loader.py", line 44, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\pyjade\ext\django\loader.py", line 70, in load_template
    template, origin = self.find_template(template_name, template_dirs)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\pyjade\ext\django\loader.py", line 38, in find_template
    template, display_name = loader(name, dirs)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\loader.py", line 44, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\loader.py", line 50, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\loader.py", line 156, in get_template_from_string
    return Template(source, origin, name)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\base.py", line 132, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\base.py", line 162, in compile_string
    return parser.parse()
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\base.py", line 290, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\templatetags\static.py", line 154, in do_static
    return StaticNode.handle_token(parser, token)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\templatetags\static.py", line 127, in handle_token
    path = parser.compile_filter(bits[1])
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\base.py", line 372, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\base.py", line 588, in __init__
    "from '%s'" % (token[upto:], token))
TemplateSyntaxError: Could not parse the remainder: '/bootstrap.min.css' from 'css/bootstrap.min.css'
Internal Server Error: /maparea/
Traceback (most recent call last):
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Larisse\Documents\Workspace\fross\altaflora\maparea\views.py", line 16, in wrapper
    return method(request)
  File "C:\Users\Larisse\Documents\Workspace\fross\altaflora\maparea\views.py", line 32, in index
    return render(request, 'maparea/index.html', context)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\shortcuts.py", line 48, in render
    return HttpResponse(loader.render_to_string(*args, **kwargs),
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\loader.py", line 170, in render_to_string
    t = get_template(template_name, dirs)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\loader.py", line 144, in get_template
    template, origin = find_template(template_name, dirs)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\loader.py", line 132, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\loader.py", line 44, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\pyjade\ext\django\loader.py", line 70, in load_template
    template, origin = self.find_template(template_name, template_dirs)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\pyjade\ext\django\loader.py", line 38, in find_template
    template, display_name = loader(name, dirs)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\loader.py", line 44, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\loader.py", line 50, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\loader.py", line 156, in get_template_from_string
    return Template(source, origin, name)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\base.py", line 132, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\base.py", line 162, in compile_string
    return parser.parse()
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\base.py", line 290, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\templatetags\static.py", line 154, in do_static
    return StaticNode.handle_token(parser, token)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\templatetags\static.py", line 127, in handle_token
    path = parser.compile_filter(bits[1])
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\base.py", line 372, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\base.py", line 588, in __init__
    "from '%s'" % (token[upto:], token))
TemplateSyntaxError: Could not parse the remainder: '/css/bootstrap.min.css' from '/css/bootstrap.min.css'
Internal Server Error: /maparea/
Traceback (most recent call last):
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Larisse\Documents\Workspace\fross\altaflora\maparea\views.py", line 16, in wrapper
    return method(request)
  File "C:\Users\Larisse\Documents\Workspace\fross\altaflora\maparea\views.py", line 32, in index
    return render(request, 'maparea/index.html', context)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\shortcuts.py", line 48, in render
    return HttpResponse(loader.render_to_string(*args, **kwargs),
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\loader.py", line 170, in render_to_string
    t = get_template(template_name, dirs)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\loader.py", line 144, in get_template
    template, origin = find_template(template_name, dirs)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\loader.py", line 132, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\loader.py", line 44, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\pyjade\ext\django\loader.py", line 70, in load_template
    template, origin = self.find_template(template_name, template_dirs)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\pyjade\ext\django\loader.py", line 38, in find_template
    template, display_name = loader(name, dirs)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\loader.py", line 44, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\loader.py", line 50, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\loader.py", line 156, in get_template_from_string
    return Template(source, origin, name)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\base.py", line 132, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\base.py", line 162, in compile_string
    return parser.parse()
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\base.py", line 290, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\templatetags\static.py", line 154, in do_static
    return StaticNode.handle_token(parser, token)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\templatetags\static.py", line 127, in handle_token
    path = parser.compile_filter(bits[1])
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\base.py", line 372, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\base.py", line 588, in __init__
    "from '%s'" % (token[upto:], token))
TemplateSyntaxError: Could not parse the remainder: '/font-awesome.min.css' from 'css/font-awesome.min.css'
Not Found: /maparea/img/logo2.png
Not Found: /maparea/js/api/tweet.php
Not Found: /maparea/js/api/tweet.php
Not Found: /maparea/js/api/tweet.php
Not Found: /maparea/js/api/tweet.php
Not Found: /maparea/js/api/tweet.php
Not Found: /maparea/js/api/tweet.php
Not Found: /maparea/js/api/tweet.php
Not Found: /maparea/js/api/tweet.php
Not Found: /maparea/js/api/tweet.php
Not Found: /maparea/js/api/tweet.php
Not Found: /maparea/js/api/tweet.php
Not Found: /maparea/js/api/tweet.php
Not Found: /maparea/js/api/tweet.php
Not Found: /maparea/js/api/tweet.php
Not Found: /maparea/js/api/tweet.php
Not Found: /maparea/js/api/tweet.php
Not Found: /maparea/js/api/tweet.php
Not Found: /maparea/js/api/tweet.php
Not Found: /maparea/js/api/tweet.php
Not Found: /maparea/js/api/tweet.php
Not Found: /maparea/js/api/tweet.php
Internal Server Error: /maparea/
Traceback (most recent call last):
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Larisse\Documents\Workspace\fross\altaflora\maparea\views.py", line 16, in wrapper
    return method(request)
  File "C:\Users\Larisse\Documents\Workspace\fross\altaflora\maparea\views.py", line 32, in index
    return render(request, 'maparea/index.html', context)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\shortcuts.py", line 48, in render
    return HttpResponse(loader.render_to_string(*args, **kwargs),
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\loader.py", line 170, in render_to_string
    t = get_template(template_name, dirs)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\loader.py", line 144, in get_template
    template, origin = find_template(template_name, dirs)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\loader.py", line 132, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\loader.py", line 44, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\pyjade\ext\django\loader.py", line 70, in load_template
    template, origin = self.find_template(template_name, template_dirs)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\pyjade\ext\django\loader.py", line 38, in find_template
    template, display_name = loader(name, dirs)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\loader.py", line 44, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\loader.py", line 50, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\loader.py", line 156, in get_template_from_string
    return Template(source, origin, name)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\base.py", line 132, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\base.py", line 162, in compile_string
    return parser.parse()
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\base.py", line 290, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\templatetags\static.py", line 154, in do_static
    return StaticNode.handle_token(parser, token)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\templatetags\static.py", line 127, in handle_token
    path = parser.compile_filter(bits[1])
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\base.py", line 372, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\base.py", line 588, in __init__
    "from '%s'" % (token[upto:], token))
TemplateSyntaxError: Could not parse the remainder: 'async' from ''js/jquery.map.js'async'
Not Found: /maparea/js/api/tweet.php
Not Found: /maparea/js/api/tweet.php
Not Found: /maparea/js/api/tweet.php
Not Found: /maparea/js/api/tweet.php
Not Found: /maparea/js/api/tweet.php
Not Found: /maparea/js/api/tweet.php
Not Found: /maparea/js/api/tweet.php
Not Found: /maparea/js/api/tweet.php
Not Found: /favicon.ico
Not Found: /login
Not Found: /favicon.ico
Internal Server Error: /maparea/
Traceback (most recent call last):
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Larisse\Documents\Workspace\fross\altaflora\maparea\views.py", line 16, in wrapper
    return method(request)
  File "C:\Users\Larisse\Documents\Workspace\fross\altaflora\maparea\views.py", line 32, in index
    return render(request, 'maparea/index.html', context)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\shortcuts.py", line 48, in render
    return HttpResponse(loader.render_to_string(*args, **kwargs),
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\loader.py", line 178, in render_to_string
    return t.render(context_instance)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\base.py", line 148, in render
    return self._render(context)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\base.py", line 142, in _render
    return self.nodelist.render(context)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\base.py", line 844, in render
    bit = self.render_node(node, context)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\debug.py", line 80, in render_node
    return node.render(context)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\defaulttags.py", line 458, in render
    six.reraise(*exc_info)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\defaulttags.py", line 444, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=context.current_app)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\core\urlresolvers.py", line 547, in reverse
    key)
NoReverseMatch: u'maparea' is not a registered namespace
Not Found: /favicon.ico
Internal Server Error: /maparea/
Traceback (most recent call last):
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Larisse\Documents\Workspace\fross\altaflora\maparea\views.py", line 16, in wrapper
    return method(request)
  File "C:\Users\Larisse\Documents\Workspace\fross\altaflora\maparea\views.py", line 32, in index
    return render(request, 'maparea/index.html', context)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\shortcuts.py", line 48, in render
    return HttpResponse(loader.render_to_string(*args, **kwargs),
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\loader.py", line 170, in render_to_string
    t = get_template(template_name, dirs)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\loader.py", line 144, in get_template
    template, origin = find_template(template_name, dirs)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\loader.py", line 132, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\loader.py", line 44, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\pyjade\ext\django\loader.py", line 70, in load_template
    template, origin = self.find_template(template_name, template_dirs)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\pyjade\ext\django\loader.py", line 38, in find_template
    template, display_name = loader(name, dirs)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\loader.py", line 44, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\loader.py", line 50, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\loader.py", line 156, in get_template_from_string
    return Template(source, origin, name)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\base.py", line 132, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\base.py", line 162, in compile_string
    return parser.parse()
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\base.py", line 290, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\defaulttags.py", line 974, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\defaulttags.py", line 906, in __init__
    super(TemplateIfParser, self).__init__(*args, **kwargs)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\smartif.py", line 164, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\smartif.py", line 175, in translate_token
    return self.create_var(token)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\defaulttags.py", line 909, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\base.py", line 372, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\base.py", line 588, in __init__
    "from '%s'" % (token[upto:], token))
TemplateSyntaxError: Could not parse the remainder: '=="admin"' from 'username=="admin"'
Internal Server Error: /maparea/
Traceback (most recent call last):
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Larisse\Documents\Workspace\fross\altaflora\maparea\views.py", line 16, in wrapper
    return method(request)
  File "C:\Users\Larisse\Documents\Workspace\fross\altaflora\maparea\views.py", line 32, in index
    return render(request, 'maparea/index.html', context)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\shortcuts.py", line 48, in render
    return HttpResponse(loader.render_to_string(*args, **kwargs),
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\loader.py", line 170, in render_to_string
    t = get_template(template_name, dirs)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\loader.py", line 144, in get_template
    template, origin = find_template(template_name, dirs)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\loader.py", line 132, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\loader.py", line 44, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\pyjade\ext\django\loader.py", line 70, in load_template
    template, origin = self.find_template(template_name, template_dirs)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\pyjade\ext\django\loader.py", line 38, in find_template
    template, display_name = loader(name, dirs)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\loader.py", line 44, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\loader.py", line 50, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\loader.py", line 156, in get_template_from_string
    return Template(source, origin, name)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\base.py", line 132, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\base.py", line 162, in compile_string
    return parser.parse()
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\base.py", line 290, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\defaulttags.py", line 974, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\defaulttags.py", line 906, in __init__
    super(TemplateIfParser, self).__init__(*args, **kwargs)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\smartif.py", line 164, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\smartif.py", line 175, in translate_token
    return self.create_var(token)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\defaulttags.py", line 909, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\base.py", line 372, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\Larisse\Documents\Workspace\fross\env4fross\lib\site-packages\django\template\base.py", line 588, in __init__
    "from '%s'" % (token[upto:], token))
TemplateSyntaxError: Could not parse the remainder: '{{' from '{{'
